name: build and test

on: 
  push:
  pull_request:
    branches: [ main ]
    paths: 
      - '**.cs'
      - '**.csproj'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configurations Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
